#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 04 17:27:31 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}